Add utility function to get image repo and tag from image reference
gardener/component-spec pull request #32
Opened 2021-02-23 11:45 UTC by danielfoehrKn

**What this PR does / why we need it**:

Adding a simple utility function to get image repo and tag from an image reference.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2021-02-25 11:18 UTC, danielfoehrKn commented
@schrodit

2021-02-25 13:47 UTC, schrodit requested changes

2021-02-25 13:47 UTC, schrodit commented on bindings-go/apis/v2/cdutils/resources.go
> +	// e.g eu.gcr.io/gardener-project:5000/gardener/gardenlet
```suggestion
	// e.g eu.gcr.io:5000/gardener-project/gardener/gardenlet
```

2021-02-25 13:47 UTC, schrodit commented on bindings-go/apis/v2/cdutils/resources.go
> +func GetRepositoryAndTagFromReference(imageReference string) (string, string, error) {
you should also consider hashes liek `eu.gc.rio/gardener-project/gardenlet@sha256:12345`

2021-03-02 15:31 UTC, schrodit approved these changes
/lgtm
looks good now

2021-03-02 15:35 UTC, merged